
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false
  
domain: Maths_PGR_Poster.github.io
url: https://Maths_PGR_Poster.github.io 

title: Poster Website 
description: This is a place where I talk about my poster! #here I am writing a comment 

