
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-github-metadata
github:
  is_project_page: false
  
domain: Maths_PGR_Poster.github.io
url: https://Maths_PGR_Poster.github.io 

title: The Effects of Compliance on the Stability of Jets and Wakes
description: This page contains resources that supllement my Maths PGR Conference Poster. #here I am writing a comment 


