
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

domain: Maths_PGR_Poster.github.io
url: https://Maths_PGR_Poster.github.io
